version: "2"
services:
  application:
    image: debian:jessie
    volumes:
        - ./:/var/www/symfony
    tty: true
  db:
    image: mysql
    ports:
        - 3001:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
        MYSQL_USER: user
        MYSQL_PASSWORD: root
  php:
    build: docker/php7
    ports:
        - 9000:9000
    volumes_from:
      - application
    links:
      - db
  nginx:
    build: docker/nginx
    ports:
        - 8001:80
    links:
        - php
    volumes_from:
        - application
    volumes:
        - ./var/logs/nginx/:/var/log/nginx